Updating dockerfile for security and best practices. Reduced to 190 MB

diff --git a/mongo-unload-service/Dockerfile b/mongo-unload-service/Dockerfile
--- a/mongo-unload-service/Dockerfile
+++ b/mongo-unload-service/Dockerfile
@@ -1,26 +1,55 @@
-# pull uvicorn-gunicorn-fast-api-slim image that is optimised for performance
-FROM python:3.9-slim
+FROM python:3.9-slim as build
 
-# set environment variables
-ENV PYTHONDONTWRITEBYTECODE 1
-ENV PYTHONUNBUFFERED 1
-ENV MODULE_NAME=src.main
-ENV PORT=8080
-ENV LOG_LEVEL=debug
-ENV PYTHONPATH=/app
+WORKDIR /app
 
-# for log file
-RUN mkdir -p /opt/delphix/logs/
+ENV PIP_DEFAULT_TIMEOUT=100 \
+    # Allow statements and log messages to immediately appear
+    PYTHONUNBUFFERED=1 \
+    # disable a pip version check to reduce run-time & log-spam
+    PIP_DISABLE_PIP_VERSION_CHECK=1 \
+    # cache is useless in docker image, so disable to reduce image size
+    PIP_NO_CACHE_DIR=1 \
+    POETRY_VERSION=1.5.1
 
-COPY requirements.txt /tmp/requirements.txt
-RUN pip install --no-cache-dir -r /tmp/requirements.txt
+COPY pyproject.toml poetry.lock ./
 
-RUN mkdir -p /app
+RUN pip install --no-cache-dir "poetry==$POETRY_VERSION"  \
+    && poetry install --without dev --no-root --no-ansi --no-interaction \
+    && poetry export --without dev -o requirements.txt \
+    && pip uninstall --yes poetry
 
+
+FROM python:3.9-slim as final
+
+WORKDIR /app
+
+COPY --from=build /app/requirements.txt .
+
+# env variables for docker container to recognize the app
+ENV PIP_DEFAULT_TIMEOUT=100 \
+    # Allow statements and log messages to immediately appear
+    PYTHONUNBUFFERED=1 \
+    # disable a pip version check to reduce run-time & log-spam
+    PIP_DISABLE_PIP_VERSION_CHECK=1 \
+    # cache is useless in docker image, so disable to reduce image size
+    PIP_NO_CACHE_DIR=1 \
+    MODULE_NAME=src.main \
+    PORT=8080 \
+    LOG_LEVEL=debug
+
+# Create a non-root user
+# Upgrade the package index and install security upgrades
+# Install python dependencies
 # Install MongoDB tools and mongosh utility
-# Install dependencies
-RUN apt-get update && \
+# Clean up
+# Create folder for log and assign permissions
+RUN set -ex &&  \
+    addgroup --system --gid 1001 appgroup &&  \
+    adduser --system --uid 1001 --gid 1001 --no-create-home appuser && \
+    apt-get update && \
+    apt-get upgrade -y && \
     apt-get install -y wget && \
+    pip install --no-cache-dir -r requirements.txt && \
     wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-rhel80-x86_64-100.7.2.tgz && \
     wget https://downloads.mongodb.com/compass/mongosh-1.10.0-linux-x64.tgz && \
     tar -zxvf mongodb-database-tools-rhel80-x86_64-100.7.2.tgz -C /app && \
@@ -33,13 +62,15 @@ RUN apt-get update && \
     apt-get remove -y wget && \
     apt-get autoremove -y && \
     apt-get clean -y && \
-    rm -rf /var/lib/apt/lists/*
+    rm -rf /var/lib/apt/lists/* && \
+    mkdir -p /opt/delphix/logs/ &&  \
+    chown -R appuser:appgroup /opt/delphix/logs/
 
 COPY ./container_conf/app_files/* /app
 COPY ./container_conf/root_files/* /
-
 COPY ./src /app/src
 
-WORKDIR /app
-ENTRYPOINT ["../start.sh"]
+# Set the user to run the application
+USER appuser
 
+ENTRYPOINT ["../start.sh"]
